### ISSUE TITLE
Window title is able to clip through the Clock (and potentially other status bar elements)

### ISSUE THREAD

**Issue by omaemae** [cyberos/cyber-statusbar#1]
![image](https://user-images.githubusercontent.com/17727163/102056466-b731c300-3dec-11eb-9eb1-2ba59cabb579.png)
Possible solution would be anchoring the title label to the left side of the Clock.

**Comment by omaemae** [comment]
![image](https://user-images.githubusercontent.com/17727163/102056787-2f988400-3ded-11eb-96be-b0316f975278.png)
That's already being done, hmm.

**Comment by omaemae** [comment]
Setting `clip: true` is a nice temporary solution, but it cuts the text abruptly instead of cleanly with "...", will look into `elide`.

**Comment by omaemae** [comment]
Yup, `elide` + `clip` fixes it.
![image](https://user-images.githubusercontent.com/17727163/102057320-09bfaf00-3dee-11eb-8cd7-df8f0b875b31.png)

**Comment by rekols** [comment]
:+1:
